---
title: "Instacart Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    source_code: embed
---

```{r setup, include=FALSE}
library(tidyverse)
library(p8105.datasets)
library(flexdashboard)
library(plotly)
```

```{r, include = FALSE}
data("instacart")
```

Column {data-width=650}
-----------------------------------------------------------------------

### Chart A

```{r}
instacart %>%
  count(aisle) %>%
  filter(n < 10000) %>% 
  mutate(aisle = fct_reorder(aisle, n)) %>% 
  plot_ly(
    x = ~aisle, y = ~n,
    type = "bar")
```

Column {data-width=350}
-----------------------------------------------------------------------

### Chart B

```{r}
instacart %>%
  count(product_name) %>% 
  filter(n > 3000) %>% 
  mutate(product_name = fct_reorder(product_name, n)) %>% 
  plot_ly(
    x = ~product_name, y = ~n,
    type = "scatter", mode = "markers",
    alpha = .5
  )
```

### Chart C

```{r}
instacart %>% 
  group_by(department) %>% 
  count() %>% 
  mutate(department = fct_reorder(department, n)) %>% 
  plot_ly(
    x = ~department, y = ~n,
    type = "scatter", mode = "lin")
```

